# Generated by Django 4.2 on 2023-04-24 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
